### ISSUE TITLE
Drop events older than some threshold

### ISSUE THREAD

**Issue by joshuaspence** [logstash-plugins/logstash-filter-drop#11]
We are in the process of rolling out Filebeat and we have some long-running instances in our production environment that don't have `logrotate` configured. As such, when Filebeat is installed on these instances we end up sending years worth of logs to our ELK stack. This is a waste of resources and has occasionally caused Elasticsearch stability issues. We have a curator setup which runs every hour and deletes Elasticsearch indices older than 14 days. As a result, these old log messages exist in our Elasticsearch cluster for no more than 60 minutes before they are deleted.

I want to configure Logstash to just completely drop messages that are older than 30 days old. It seems to me that the `drop` filter is the ideal candidate for this type of behavior.

**Comment by joshuaspence** [comment]
I'm happy to submit a pull request if this functionality would be accepted upstream.

**Comment by ph** [comment]
@joshuaspence I am not sure we need to add that feature to the drop filter, the drop is only meant to be used in a conditional statement.

I think what we actually need is a filter that can calculate how old an event is then we can use the added field with a conditional to route it to the drop filter. WDYT?

**Comment by ph** [comment]
Actually, I think it should be another filter, because it would open the flow to more logic options,
lets say that you want to send old log to a specific ES cluster for cold storage and the newest in the hot cluster, or a different index.

**Comment by joshuaspence** [comment]
Sure, I would be happy with something like this instead:

```
filter {
  age {
    target => "event_age"
  }

  if [event_age] > 9999 {
    drop {}
  }
}
```

**Comment by joshuaspence** [comment]
How would a different filter work exactly?

**Comment by ph** [comment]
@joshuaspence love the idea and the name, I've seen people use the ruby filter to do just that.

> How would a different filter work exactly?

It just a matter of creating a new personal repo and an issue on the main logstash repo when it's done if you want to move it to the `logstash-plugins` organization you will still be the maintainer.

We have doc about writing your own filter there https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_filter_plugin.html

am I answering your question correctly?

**Comment by joshuaspence** [comment]
Yep thanks, I'll give it a go.

**Comment by ph** [comment]
I will close this issue since we wont do it in the drop filter.
